defaultBaseImage: alpine

builds:
- id: frpp
  dir: .
  main: ./cmd/frpp
  ldflags:
  - -s -w
  - -X fysj.net/v2/conf.buildDate={{.Date}}
  - -X fysj.net/v2/conf.gitCommit={{.Git.FullCommit}}
  - -X fysj.net/v2/conf.gitVersion={{.Git.Tag}}
  - -X fysj.net/v2/conf.gitBranch={{.Git.Branch}}

defaultPlatforms:
- all